=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'cgi'

module Vobiz
  class TrunkApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Delete a Credential
    # Delete a SIP credential. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_credentials_credential_id_delete(account_id, opts = {})
      api_v1_account_account_id_credentials_credential_id_delete_with_http_info(account_id, opts)
      nil
    end

    # Delete a Credential
    # Delete a SIP credential. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_credentials_credential_id_delete_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_credentials_credential_id_delete ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_credentials_credential_id_delete"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/credentials/:credential_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_credentials_credential_id_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_credentials_credential_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update a Credential
    # Update SIP credential settings.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_credentials_credential_id_put(account_id, opts = {})
      api_v1_account_account_id_credentials_credential_id_put_with_http_info(account_id, opts)
      nil
    end

    # Update a Credential
    # Update SIP credential settings.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_credentials_credential_id_put_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_credentials_credential_id_put ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_credentials_credential_id_put"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/credentials/:credential_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_credentials_credential_id_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_credentials_credential_id_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Credential
    # Create SIP authentication credentials for a trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_credentials_post(account_id, opts = {})
      api_v1_account_account_id_credentials_post_with_http_info(account_id, opts)
      nil
    end

    # Create Credential
    # Create SIP authentication credentials for a trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_credentials_post_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_credentials_post ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_credentials_post"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/credentials'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_credentials_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_credentials_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete an IP ACL
    # Delete an IP ACL entry. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_ip_acl_ip_acl_id_delete(account_id, opts = {})
      api_v1_account_account_id_ip_acl_ip_acl_id_delete_with_http_info(account_id, opts)
      nil
    end

    # Delete an IP ACL
    # Delete an IP ACL entry. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_ip_acl_ip_acl_id_delete_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_delete ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_delete"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/ip-acl/:ip_acl_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_ip_acl_ip_acl_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an IP ACL
    # Update an IP ACL entry.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_ip_acl_ip_acl_id_put(account_id, opts = {})
      api_v1_account_account_id_ip_acl_ip_acl_id_put_with_http_info(account_id, opts)
      nil
    end

    # Update an IP ACL
    # Update an IP ACL entry.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_ip_acl_ip_acl_id_put_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_put ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_put"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/ip-acl/:ip_acl_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_ip_acl_ip_acl_id_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_ip_acl_ip_acl_id_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create IP ACL
    # Create an IP Access Control List entry for trunk authentication.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_ip_acl_post(account_id, opts = {})
      api_v1_account_account_id_ip_acl_post_with_http_info(account_id, opts)
      nil
    end

    # Create IP ACL
    # Create an IP Access Control List entry for trunk authentication.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_ip_acl_post_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_ip_acl_post ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_ip_acl_post"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/ip-acl'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_ip_acl_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_ip_acl_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Unassign Number from Trunk
    # Remove a phone number from its trunk assignment. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_numbers_assign_delete(account_id, opts = {})
      api_v1_account_account_id_numbers_assign_delete_with_http_info(account_id, opts)
      nil
    end

    # Unassign Number from Trunk
    # Remove a phone number from its trunk assignment. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_numbers_assign_delete_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_numbers_assign_delete ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_numbers_assign_delete"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/numbers/{}/assign'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_numbers_assign_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_numbers_assign_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Assign Number to Trunk
    # Assign a phone number to a trunk group.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_numbers_assign_post(account_id, opts = {})
      api_v1_account_account_id_numbers_assign_post_with_http_info(account_id, opts)
      nil
    end

    # Assign Number to Trunk
    # Assign a phone number to a trunk group.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_numbers_assign_post_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_numbers_assign_post ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_numbers_assign_post"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/numbers/{}/assign'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_numbers_assign_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_numbers_assign_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Origination URI
    # Create an origination URI for inbound SIP routing.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_origination_uris_post(account_id, opts = {})
      api_v1_account_account_id_origination_uris_post_with_http_info(account_id, opts)
      nil
    end

    # Create Origination URI
    # Create an origination URI for inbound SIP routing.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_origination_uris_post_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_origination_uris_post ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_origination_uris_post"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/origination-uris'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_origination_uris_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_origination_uris_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete an Origination URI
    # Delete an origination URI. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_origination_uris_uri_id_delete(account_id, opts = {})
      api_v1_account_account_id_origination_uris_uri_id_delete_with_http_info(account_id, opts)
      nil
    end

    # Delete an Origination URI
    # Delete an origination URI. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_origination_uris_uri_id_delete_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_origination_uris_uri_id_delete ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_origination_uris_uri_id_delete"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/origination-uris/:uri_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_origination_uris_uri_id_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_origination_uris_uri_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update an Origination URI
    # Update an origination URI.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_origination_uris_uri_id_put(account_id, opts = {})
      api_v1_account_account_id_origination_uris_uri_id_put_with_http_info(account_id, opts)
      nil
    end

    # Update an Origination URI
    # Update an origination URI.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_origination_uris_uri_id_put_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_origination_uris_uri_id_put ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_origination_uris_uri_id_put"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/origination-uris/:uri_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_origination_uris_uri_id_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_origination_uris_uri_id_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List All Credentials
    # Retrieve all SIP credentials.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [nil]
    def api_v1_account_account_id_trunks_credentials_get(account_id, opts = {})
      api_v1_account_account_id_trunks_credentials_get_with_http_info(account_id, opts)
      nil
    end

    # List All Credentials
    # Retrieve all SIP credentials.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_credentials_get_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_credentials_get ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_credentials_get"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/credentials'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_credentials_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_credentials_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List All Trunks
    # Retrieve all trunks.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [nil]
    def api_v1_account_account_id_trunks_get(account_id, opts = {})
      api_v1_account_account_id_trunks_get_with_http_info(account_id, opts)
      nil
    end

    # List All Trunks
    # Retrieve all trunks.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_get_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_get ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_get"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List All IP ACLs
    # Retrieve all IP ACL entries.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [nil]
    def api_v1_account_account_id_trunks_ip_acl_get(account_id, opts = {})
      api_v1_account_account_id_trunks_ip_acl_get_with_http_info(account_id, opts)
      nil
    end

    # List All IP ACLs
    # Retrieve all IP ACL entries.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_ip_acl_get_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_ip_acl_get ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_ip_acl_get"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/ip-acl'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_ip_acl_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_ip_acl_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List All Origination URIs
    # Retrieve all origination URIs.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [nil]
    def api_v1_account_account_id_trunks_origination_uris_get(account_id, opts = {})
      api_v1_account_account_id_trunks_origination_uris_get_with_http_info(account_id, opts)
      nil
    end

    # List All Origination URIs
    # Retrieve all origination URIs.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Integer] :limit Results per page
    # @option opts [Integer] :offset Pagination offset
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_origination_uris_get_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_origination_uris_get ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_origination_uris_get"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/origination-uris'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_origination_uris_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_origination_uris_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Trunk
    # Create a new SIP trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_trunks_post(account_id, opts = {})
      api_v1_account_account_id_trunks_post_with_http_info(account_id, opts)
      nil
    end

    # Create Trunk
    # Create a new SIP trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_post_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_post ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_post"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete a Trunk
    # Delete a trunk. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_trunks_trunk_id_delete(account_id, opts = {})
      api_v1_account_account_id_trunks_trunk_id_delete_with_http_info(account_id, opts)
      nil
    end

    # Delete a Trunk
    # Delete a trunk. Returns 204 No Content.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_trunk_id_delete_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_trunk_id_delete ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_trunk_id_delete"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/:trunk_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_trunk_id_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_trunk_id_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Retrieve a Trunk
    # Get details of a specific trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [nil]
    def api_v1_account_account_id_trunks_trunk_id_get(account_id, opts = {})
      api_v1_account_account_id_trunks_trunk_id_get_with_http_info(account_id, opts)
      nil
    end

    # Retrieve a Trunk
    # Get details of a specific trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_trunk_id_get_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_trunk_id_get ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_trunk_id_get"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/:trunk_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_trunk_id_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_trunk_id_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Update a Trunk
    # Update an existing trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [nil]
    def api_v1_account_account_id_trunks_trunk_id_put(account_id, opts = {})
      api_v1_account_account_id_trunks_trunk_id_put_with_http_info(account_id, opts)
      nil
    end

    # Update a Trunk
    # Update an existing trunk.
    # @param account_id [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_auth_id 
    # @option opts [String] :x_auth_token 
    # @option opts [String] :content_type 
    # @option opts [Object] :body 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def api_v1_account_account_id_trunks_trunk_id_put_with_http_info(account_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrunkApi.api_v1_account_account_id_trunks_trunk_id_put ...'
      end
      # verify the required parameter 'account_id' is set
      if @api_client.config.client_side_validation && account_id.nil?
        fail ArgumentError, "Missing the required parameter 'account_id' when calling TrunkApi.api_v1_account_account_id_trunks_trunk_id_put"
      end
      # resource path
      local_var_path = '/api/v1/account/{account_id}/trunks/:trunk_id'.sub('{' + 'account_id' + '}', CGI.escape(account_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end
      header_params[:'X-Auth-ID'] = opts[:'x_auth_id'] if !opts[:'x_auth_id'].nil?
      header_params[:'X-Auth-Token'] = opts[:'x_auth_token'] if !opts[:'x_auth_token'].nil?
      header_params[:'Content-Type'] = opts[:'content_type'] if !opts[:'content_type'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'body'])

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuthID', 'ApiKeyAuthToken']

      new_options = opts.merge(
        :operation => :"TrunkApi.api_v1_account_account_id_trunks_trunk_id_put",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrunkApi#api_v1_account_account_id_trunks_trunk_id_put\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
