=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = Vobiz::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(Vobiz::AccountApi)
    end
  end

  # unit tests for api_v1_account_account_id_balance_inr_get
  # Get Balance
  # Retrieve the balance for a specific account and currency. Replace &#39;INR&#39; with your currency code.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_account_id_balance_inr_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_account_id_transactions_get
  # Get Transactions
  # Retrieve a list of transactions for a specific account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Integer] :limit Records per page (default: 50)
  # @option opts [Integer] :offset Pagination offset (default: 0)
  # @return [nil]
  describe 'api_v1_account_account_id_transactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_concurrency_get
  # Get Concurrency
  # Retrieve current concurrent call count and capacity.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_concurrency_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_auth_me_get
  # Retrieve Account Details
  # Retrieve complete account details including pricing tier, credentials, and account settings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_auth_me_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
