=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::CallApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallApi' do
  before do
    # run before each test
    @api_instance = Vobiz::CallApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallApi' do
    it 'should create an instance of CallApi' do
      expect(@api_instance).to be_instance_of(Vobiz::CallApi)
    end
  end

  # unit tests for api_v1_account_auth_id_call_delete
  # Hang Up a Call
  # Terminate an active call. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_dtmf_post
  # Send DTMF Digits
  # Send DTMF digits to an active call for automated IVR navigation.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_dtmf_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_get
  # Retrieve All Queued Calls
  # Get a list of all call UUIDs for calls currently queued and waiting to connect. Max 20 results.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [String] :status Must be &#39;queued&#39;
  # @return [nil]
  describe 'api_v1_account_auth_id_call_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_get_0
  # Retrieve a Queued Call
  # Get details of a specific queued call.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [String] :status Must be &#39;queued&#39;
  # @return [nil]
  describe 'api_v1_account_auth_id_call_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_play_delete
  # Stop Playing Audio on a Call
  # Stop audio playback on an active call. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_play_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_play_post
  # Play Audio on a Call
  # Play audio file(s) during an active call.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_play_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_post
  # Make an Outbound Call
  # Initiate an outbound call to a PSTN number or SIP endpoint. Supports bulk calls (up to 1000 destinations using &lt; separator).
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_post_0
  # Transfer a Call
  # Transfer an in-progress call to a different URL for new call flow instructions.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_record_delete
  # Stop Recording a Call
  # Stop active recording(s) on a call. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_record_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_record_post
  # Start Recording a Call
  # Begin recording an active call.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_record_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_speak_delete
  # Stop Speaking Text on a Call
  # Stop text-to-speech playback. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_speak_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_call_speak_post
  # Speak Text on a Call (TTS)
  # Convert text to speech and play it during an active call. Supports 29 languages.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_call_speak_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
