=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::CDRApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CDRApi' do
  before do
    # run before each test
    @api_instance = Vobiz::CDRApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CDRApi' do
    it 'should create an instance of CDRApi' do
      expect(@api_instance).to be_instance_of(Vobiz::CDRApi)
    end
  end

  # unit tests for api_v1_account_account_id_cdr_get
  # Get Call Detail Records
  # Retrieve call detail records with filtering and pagination.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [String] :start_date Start date (YYYY-MM-DD)
  # @option opts [String] :end_date End date (YYYY-MM-DD)
  # @option opts [Integer] :per_page Results per page
  # @option opts [Integer] :page Page number
  # @return [nil]
  describe 'api_v1_account_account_id_cdr_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
