=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::ConferenceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConferenceApi' do
  before do
    # run before each test
    @api_instance = Vobiz::ConferenceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConferenceApi' do
    it 'should create an instance of ConferenceApi' do
      expect(@api_instance).to be_instance_of(Vobiz::ConferenceApi)
    end
  end

  # unit tests for api_v1_account_auth_id_conference_delete
  # Hang Up All Conferences
  # Terminate all ongoing conferences simultaneously. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_delete_0
  # Hang Up a Conference
  # Terminate a specific conference and disconnect all participants. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_delete_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_get
  # List All Conferences
  # Retrieve a list of all ongoing conferences.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_get_0
  # Retrieve a Conference
  # Get detailed information about a specific ongoing conference including all active members.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_deaf_delete
  # Undeaf a Conference Member
  # Restore audio reception for previously deafened members.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_deaf_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_deaf_post
  # Deaf a Conference Member
  # Prevent member(s) from hearing other participants.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_deaf_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_delete
  # Hang Up a Conference Member
  # Disconnect a member by terminating their call. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_kick_post
  # Kick a Conference Member
  # Disconnect a member while allowing XML flow continuation.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_kick_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_mute_delete
  # Unmute a Conference Member
  # Restore audio from previously muted members.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_mute_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_mute_post
  # Mute a Conference Member
  # Mute member(s) so others cannot hear them.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_mute_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_play_delete
  # Stop Playing Audio to a Conference Member
  # Stop audio playback for specific member(s).
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_play_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_member_play_post
  # Play Audio to a Conference Member
  # Play audio to specific member(s). Only targeted member(s) hear the audio.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_member_play_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_record_delete
  # Stop Conference Recording
  # Stop an active conference recording. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_record_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_conference_record_post
  # Start Conference Recording
  # Begin recording a conference call.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_conference_record_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
