=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::EndpointApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EndpointApi' do
  before do
    # run before each test
    @api_instance = Vobiz::EndpointApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EndpointApi' do
    it 'should create an instance of EndpointApi' do
      expect(@api_instance).to be_instance_of(Vobiz::EndpointApi)
    end
  end

  # unit tests for api_v1_account_auth_id_endpoint_delete
  # Delete an Endpoint
  # Delete an endpoint. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_endpoint_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_endpoint_get
  # List All Endpoints
  # Retrieve all endpoints with pagination.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Integer] :limit Results per page
  # @option opts [Integer] :offset Pagination offset
  # @return [nil]
  describe 'api_v1_account_auth_id_endpoint_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_endpoint_get_0
  # Retrieve an Endpoint
  # Get details of a specific endpoint.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_endpoint_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_endpoint_post
  # Create Endpoint
  # Create a new SIP endpoint.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_endpoint_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_endpoint_post_0
  # Update an Endpoint
  # Update an existing endpoint&#39;s configuration.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_endpoint_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
