=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::PhoneNumbersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PhoneNumbersApi' do
  before do
    # run before each test
    @api_instance = Vobiz::PhoneNumbersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhoneNumbersApi' do
    it 'should create an instance of PhoneNumbersApi' do
      expect(@api_instance).to be_instance_of(Vobiz::PhoneNumbersApi)
    end
  end

  # unit tests for api_v1_account_auth_id_inventory_numbers_get
  # List Inventory Numbers
  # Browse available phone numbers in inventory for purchase.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [String] :country Filter by country code
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :per_page Results per page
  # @return [nil]
  describe 'api_v1_account_auth_id_inventory_numbers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_numbers_e164_number_delete
  # Unrent a Phone Number
  # Release (unrent) a phone number from your account.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_numbers_e164_number_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_numbers_get
  # List Account Phone Numbers
  # Retrieve all phone numbers associated with your account.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_numbers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_numbers_purchase_from_inventory_post
  # Purchase from Inventory
  # Purchase a phone number from available inventory.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_numbers_purchase_from_inventory_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
