=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::RecordingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecordingApi' do
  before do
    # run before each test
    @api_instance = Vobiz::RecordingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecordingApi' do
    it 'should create an instance of RecordingApi' do
      expect(@api_instance).to be_instance_of(Vobiz::RecordingApi)
    end
  end

  # unit tests for api_v1_account_account_id_recording_get
  # List All Recordings
  # Retrieve a paginated list of call recordings for your account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Integer] :limit Records per request (default: 20, max: 100)
  # @option opts [Integer] :offset Pagination offset (default: 0)
  # @option opts [String] :call_uuid Filter by specific call UUID
  # @option opts [String] :recording_type Filter by type: trunk or extension
  # @return [nil]
  describe 'api_v1_account_account_id_recording_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_export_recording_post
  # Export Historical Recordings
  # Export recordings as a downloadable archive sent via email (async). Returns 202 Accepted.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_account_auth_id_export_recording_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_recording_bulk_delete_delete
  # Bulk Delete Recordings
  # Delete multiple recordings matching filter criteria (async operation). Returns 202 Accepted.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [String] :add_time__gte Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)
  # @option opts [String] :add_time__lte Delete recordings on/before this date
  # @option opts [String] :call_uuid Delete recordings for specific call UUID
  # @option opts [String] :from_number Delete by caller number (partial match)
  # @option opts [String] :to_number Delete by destination number (partial match)
  # @option opts [String] :recording_format mp3 or wav
  # @return [nil]
  describe 'api_v1_account_auth_id_recording_bulk_delete_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_recording_delete
  # Delete a Recording
  # Permanently delete a specific recording. Returns 204 No Content.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_recording_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_account_auth_id_recording_get
  # Retrieve a Recording
  # Get detailed information about a specific recording.
  # @param auth_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_account_auth_id_recording_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
