=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Vobiz::SubAccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubAccountApi' do
  before do
    # run before each test
    @api_instance = Vobiz::SubAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubAccountApi' do
    it 'should create an instance of SubAccountApi' do
      expect(@api_instance).to be_instance_of(Vobiz::SubAccountApi)
    end
  end

  # unit tests for api_v1_accounts_account_id_sub_accounts_get
  # List All Sub-Accounts
  # Retrieve all sub-accounts.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :size Results per page
  # @option opts [Boolean] :active_only Filter active sub-accounts only
  # @return [nil]
  describe 'api_v1_accounts_account_id_sub_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_accounts_account_id_sub_accounts_post
  # Create Sub-Account
  # Create a new sub-account under the master account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_accounts_account_id_sub_accounts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_accounts_account_id_sub_accounts_sub_account_id_delete
  # Delete a Sub-Account
  # Delete a sub-account. Returns 204 No Content.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_accounts_account_id_sub_accounts_sub_account_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_accounts_account_id_sub_accounts_sub_account_id_get
  # Retrieve a Sub-Account
  # Get details of a specific sub-account.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'api_v1_accounts_account_id_sub_accounts_sub_account_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_accounts_account_id_sub_accounts_sub_account_id_put
  # Update a Sub-Account
  # Update sub-account settings.
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_auth_id 
  # @option opts [String] :x_auth_token 
  # @option opts [String] :content_type 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_v1_accounts_account_id_sub_accounts_sub_account_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
