=begin
#Vobiz API

#Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

# Common files
require 'vobiz/api_client'
require 'vobiz/api_error'
require 'vobiz/api_model_base'
require 'vobiz/version'
require 'vobiz/configuration'
require 'vobiz/access_token'
require 'vobiz/sdk/client'
require 'vobiz/xml'

# Models

# APIs
require 'vobiz/api/account_api'
require 'vobiz/api/application_api'
require 'vobiz/api/cdr_api'
require 'vobiz/api/call_api'
require 'vobiz/api/conference_api'
require 'vobiz/api/endpoint_api'
require 'vobiz/api/phone_numbers_api'
require 'vobiz/api/recording_api'
require 'vobiz/api/sub_account_api'
require 'vobiz/api/trunk_api'

module Vobiz
  Client = SDK::Client

  class << self
    # Customize default settings for the SDK using block.
    #   Vobiz.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
